### ISSUE TITLE
Waf 2.0.12 not compliant with FIPS systems

### ISSUE THREAD

**Issue by aneesas** [ZeroCM/zcm#286]
MD5 is disabled for systems subject to FIPS--see Wafissue 2213 [here](https://gitlab.com/ita1024/waf/issues/2213) and fix [here](https://gitlab.com/ita1024/waf/commit/1c7be35dc0a673467847fc0ac65b4f1fc58c00ad). The fix is included starting in Waf 2.0.14. This means ZCM with the current Waf version does not build on systems subject to FIPS.

Stack trace:
```
> ./waf configure --use-elf
Setting top to                           : /[path_to]/zcm
Setting out to                           : /[path_to]/zcm/build
Checking for 'gcc' (C compiler)          : Traceback (most recent call last):
  File "/[path_to]/zcm/.waf-2.0.12-42a92c4be92cf9831e421bf69cb61842/waflib/Scripting.py", line 119, in waf_e
    run_commands()
  File "/[path_to]/zcm/.waf-2.0.12-42a92c4be92cf9831e421bf69cb61842/waflib/Scripting.py", line 179, in run_c
    ctx=run_command(cmd_name)
  File "/[path_to]/zcm/.waf-2.0.12-42a92c4be92cf9831e421bf69cb61842/waflib/Scripting.py", line 170, in run_c
    ctx.execute()
  File "/[path_to]/zcm/.waf-2.0.12-42a92c4be92cf9831e421bf69cb61842/waflib/Configure.py", line 85, in execut
    super(ConfigurationContext,self).execute()
  File "/[path_to]/zcm/.waf-2.0.12-42a92c4be92cf9831e421bf69cb61842/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/[path_to]/zcm/.waf-2.0.12-42a92c4be92cf9831e421bf69cb61842/waflib/Context.py", line 128, in recurse
    self.post_recurse(node)
  File "/[path_to]/zcm/.waf-2.0.12-42a92c4be92cf9831e421bf69cb61842/waflib/Configure.py", line 161, in post_
    self.hash=Utils.h_list((self.hash,node.read('rb')))
  File "/[path_to]/zcm/.waf-2.0.12-42a92c4be92cf9831e421bf69cb61842/waflib/Utils.py", line 368, in h_list
    return md5(repr(lst)).digest()
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
```

**Comment by jbendes** [comment]
Working on it now

**Comment by jbendes** [comment]
Solved in https://github.com/ZeroCM/zcm/pull/287
